### ISSUE TITLE
Singletoane

### ISSUE THREAD

**Issue by narpaslaru** [sosig132/Store-management-system#2]
Incercati sa nu mai folositi asa de mult Singleton-ul. 

Ar fi mai interesant un Factory care sa va dea o implementare in functie de alegerea din interfata (1 sau 2) si voi in clasa care foloseste una din implementari sa apelati functiile generic, la Menu, ati apela functia start().

**Comment by sosig132** [comment]
Am adaugat Factory pentru Menu. Puteti sa imi spuneti daca este ok?
